server:
  port: 8089
  session-timeout: 60 # session
  tomcat:
    uri-encoding: utf-8 # Setting up tomcat encoding
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/DoggyPets?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: root
    password: Yyj188706
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/templates/,classpath:/static/image/,classpath:/static/,classpath:/mapper/

mybatis:
  mapper-locations: classpath:static/mapper/*.xml # The path where the configuration mapper file is located
  type-aliases-package: com.codetest.Entity # Configure all class aliases under this package
